no-resolv
no-hosts
listen-address=0.0.0.0
bind-interfaces

address=/server.cnc.local/172.20.0.10
address=/www.cnc.local/172.20.0.10
address=/api.cnc.local/172.20.0.10
address=/files.cnc.local/172.20.0.10
address=/client.cnc.local/172.20.0.20
address=/attacker.cnc.local/172.20.0.30

log-queries
log-facility=/var/log/dnsmasq.log
